"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# $username\
#  $directory\
# $c\
# $cpp\
# $python\
# $rust\
# $shell\
# $git_branch\
# $package\
# $battery\
# $cmd_duration \
#  $character\
# """

format = """
$shell \
$directory \
$git_branch \
$character\
"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[î»¾](bold green) [î»¾](bold yellow) [ ï„](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[î»¾ âœ—](bold red) '

[custom.ghost_pertama]
format = 'î»¾(bold green)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[c]
format = 'via [$name $version]($style)'

[cpp]
disabled = false
format = 'via [$name $version]($style)'

[cmd_duration]
min_time = 500
format = 'on [$duration](bold yellow)'

[python]
symbol = 'ğŸ '
pyenv_version_name = true

[shell]
fish_indicator = 'ó°ˆº '
zsh_indicator = 'î•'
powershell_indicator = 'ï‘ _'
unknown_indicator = 'ï‘ _'
style = 'cyan bold'
disabled = false

[rust]
format = 'via [âš™ï¸ $version](red bold)'

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '


[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchai" }

